FROM registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift

ADD binary/apache-rocketmq-all /home/jboss
ENV ROCKETMQ_HOME /home/jboss
ENV JAVA_OPT '-Xms1g -Xmx1g -Xmn512mb'
EXPOSE 9876
ENTRYPOINT ${ROCKETMQ_HOME}/bin/mqnamesrvdocker
